#!/usr/bin/env bash
#a shell script that will print Best School 9 times and hi one time


i=1
while [ $i -lt 11 ]
do
    
    if [ $i -eq 8 ] 
    then
        echo "good luck"
    elif [ $i -eq 4 ]
    then
        echo "bad luck"
    else
        echo "Best School"
    fi
    ((i++))
done