#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes:

minutes=1
hours=0
while [ $minutes -lt 60 ] || [ $hours -lt 13 ]; do
    if [ $minutes -eq 60 ] && [ $hours -lt 13 ]; then
        echo "Hour: $hours"
        ((hours++))
        minutes=1
    else
        echo "$minutes"
        ((minutes++))
    fi
done